// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ner.proto

package ner_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnnotateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Threshold     float32                `protobuf:"fixed32,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotateRequest) Reset() {
	*x = AnnotateRequest{}
	mi := &file_ner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotateRequest) ProtoMessage() {}

func (x *AnnotateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotateRequest.ProtoReflect.Descriptor instead.
func (*AnnotateRequest) Descriptor() ([]byte, []int) {
	return file_ner_proto_rawDescGZIP(), []int{0}
}

func (x *AnnotateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnnotateRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AnnotateRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_ner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_ner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_ner_proto_rawDescGZIP(), []int{1}
}

func (x *Span) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Span) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Span) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Span) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Span) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AnnotateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Tokens        []string               `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Spans         []*Span                `protobuf:"bytes,3,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotateResponse) Reset() {
	*x = AnnotateResponse{}
	mi := &file_ner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotateResponse) ProtoMessage() {}

func (x *AnnotateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotateResponse.ProtoReflect.Descriptor instead.
func (*AnnotateResponse) Descriptor() ([]byte, []int) {
	return file_ner_proto_rawDescGZIP(), []int{2}
}

func (x *AnnotateResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnnotateResponse) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *AnnotateResponse) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

type BatchAnnotateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Threshold     float32                `protobuf:"fixed32,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAnnotateRequest) Reset() {
	*x = BatchAnnotateRequest{}
	mi := &file_ner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAnnotateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAnnotateRequest) ProtoMessage() {}

func (x *BatchAnnotateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAnnotateRequest.ProtoReflect.Descriptor instead.
func (*BatchAnnotateRequest) Descriptor() ([]byte, []int) {
	return file_ner_proto_rawDescGZIP(), []int{3}
}

func (x *BatchAnnotateRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *BatchAnnotateRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *BatchAnnotateRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type BatchAnnotateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Annotations   []*AnnotateResponse    `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAnnotateResponse) Reset() {
	*x = BatchAnnotateResponse{}
	mi := &file_ner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAnnotateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAnnotateResponse) ProtoMessage() {}

func (x *BatchAnnotateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAnnotateResponse.ProtoReflect.Descriptor instead.
func (*BatchAnnotateResponse) Descriptor() ([]byte, []int) {
	return file_ner_proto_rawDescGZIP(), []int{4}
}

func (x *BatchAnnotateResponse) GetAnnotations() []*AnnotateResponse {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_ner_proto protoreflect.FileDescriptor

const file_ner_proto_rawDesc = "" +
	"\n" +
	"\tner.proto\x12\x03ner\"[\n" +
	"\x0fAnnotateRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x02R\tthreshold\"n\n" +
	"\x04Span\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x05R\x03end\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\"_\n" +
	"\x10AnnotateResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06tokens\x18\x02 \x03(\tR\x06tokens\x12\x1f\n" +
	"\x05spans\x18\x03 \x03(\v2\t.ner.SpanR\x05spans\"b\n" +
	"\x14BatchAnnotateRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x02R\tthreshold\"P\n" +
	"\x15BatchAnnotateResponse\x127\n" +
	"\vannotations\x18\x01 \x03(\v2\x15.ner.AnnotateResponseR\vannotations2\x8d\x01\n" +
	"\n" +
	"NERService\x127\n" +
	"\bAnnotate\x12\x14.ner.AnnotateRequest\x1a\x15.ner.AnnotateResponse\x12F\n" +
	"\rBatchAnnotate\x12\x19.ner.BatchAnnotateRequest\x1a\x1a.ner.BatchAnnotateResponseB4Z2github.com/ContinuumSolutions/nonym/pkg/ner/ner_pbb\x06proto3"

var (
	file_ner_proto_rawDescOnce sync.Once
	file_ner_proto_rawDescData []byte
)

func file_ner_proto_rawDescGZIP() []byte {
	file_ner_proto_rawDescOnce.Do(func() {
		file_ner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ner_proto_rawDesc), len(file_ner_proto_rawDesc)))
	})
	return file_ner_proto_rawDescData
}

var file_ner_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ner_proto_goTypes = []any{
	(*AnnotateRequest)(nil),       // 0: ner.AnnotateRequest
	(*Span)(nil),                  // 1: ner.Span
	(*AnnotateResponse)(nil),      // 2: ner.AnnotateResponse
	(*BatchAnnotateRequest)(nil),  // 3: ner.BatchAnnotateRequest
	(*BatchAnnotateResponse)(nil), // 4: ner.BatchAnnotateResponse
}
var file_ner_proto_depIdxs = []int32{
	1, // 0: ner.AnnotateResponse.spans:type_name -> ner.Span
	2, // 1: ner.BatchAnnotateResponse.annotations:type_name -> ner.AnnotateResponse
	0, // 2: ner.NERService.Annotate:input_type -> ner.AnnotateRequest
	3, // 3: ner.NERService.BatchAnnotate:input_type -> ner.BatchAnnotateRequest
	2, // 4: ner.NERService.Annotate:output_type -> ner.AnnotateResponse
	4, // 5: ner.NERService.BatchAnnotate:output_type -> ner.BatchAnnotateResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ner_proto_init() }
func file_ner_proto_init() {
	if File_ner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ner_proto_rawDesc), len(file_ner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ner_proto_goTypes,
		DependencyIndexes: file_ner_proto_depIdxs,
		MessageInfos:      file_ner_proto_msgTypes,
	}.Build()
	File_ner_proto = out.File
	file_ner_proto_goTypes = nil
	file_ner_proto_depIdxs = nil
}
