package profile

import (
	"fmt"
	"strings"
)

// UserIdentity captures who the user is, used to personalise LLM analysis prompts.
// All fields are optional free-text. Even partially filled, they dramatically improve
// signal scoring accuracy by giving the LLM context about what matters to the user.
type UserIdentity struct {
	Profession       string `json:"profession"`        // e.g. "Senior Product Manager, B2B SaaS"
	Industry         string `json:"industry"`           // e.g. "Software / SaaS"
	Skills           string `json:"skills"`             // e.g. "product strategy, pricing, hiring"
	CurrentGoals     string `json:"current_goals"`      // e.g. "close Q1 enterprise deals"
	IncomeModel      string `json:"income_model"`       // e.g. "salary + consulting"
	SignalPriorities string `json:"signal_priorities"`  // e.g. "client requests, investor pings"
	InferredSummary  string `json:"inferred_summary,omitempty"` // auto-generated by POST /profile/infer
}

// IdentityContext builds the USER CONTEXT block injected into LLM system prompts.
// Returns an empty string when no identity fields are populated (LLM runs without context).
func (id UserIdentity) IdentityContext() string {
	var lines []string
	if id.Profession != "" {
		lines = append(lines, fmt.Sprintf("Profession: %s", id.Profession))
	}
	if id.Industry != "" {
		lines = append(lines, fmt.Sprintf("Industry: %s", id.Industry))
	}
	if id.Skills != "" {
		lines = append(lines, fmt.Sprintf("Skills: %s", id.Skills))
	}
	if id.CurrentGoals != "" {
		lines = append(lines, fmt.Sprintf("Current Goals: %s", id.CurrentGoals))
	}
	if id.IncomeModel != "" {
		lines = append(lines, fmt.Sprintf("Income Model: %s", id.IncomeModel))
	}
	if id.SignalPriorities != "" {
		lines = append(lines, fmt.Sprintf("Signal Priorities (high → low): %s", id.SignalPriorities))
	}
	if id.InferredSummary != "" {
		lines = append(lines, fmt.Sprintf("Background: %s", id.InferredSummary))
	}
	if len(lines) == 0 {
		return ""
	}
	return "USER CONTEXT:\n" + strings.Join(lines, "\n")
}

// IsEmpty returns true when no identity fields have been populated.
func (id UserIdentity) IsEmpty() bool {
	return id.Profession == "" && id.Industry == "" && id.Skills == "" &&
		id.CurrentGoals == "" && id.IncomeModel == "" && id.SignalPriorities == "" &&
		id.InferredSummary == ""
}
