// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/activities/events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "List events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_activities.Event"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/activities/events/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Get event by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_activities.Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/activities/events/{id}/read": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Toggle read status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_activities.Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/session/lock": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Lock the screen session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/session/unlock": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Unlock the screen session",
                "parameters": [
                    {
                        "description": "SHA-256 hex of the PIN",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.unlockReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/biometrics/checkin": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "biometrics"
                ],
                "summary": "Get current check-in",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_biometrics.CheckIn"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "biometrics"
                ],
                "summary": "Update check-in",
                "parameters": [
                    {
                        "description": "Check-in data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_biometrics.CheckIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_biometrics.CheckIn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/biometrics/checkin/history": {
            "get": {
                "description": "Returns past check-ins newest first. Default limit is 7 (one week); maximum is 90.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "biometrics"
                ],
                "summary": "Check-in history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of entries to return (1–90, default 7)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_biometrics.CheckIn"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/brain/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "brain"
                ],
                "summary": "Get brain status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_brain.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/brain/sync-acknowledge": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "brain"
                ],
                "summary": "Acknowledge manual sync (clears H2HI)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_brain.KernelSnapshot"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/chat": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat with your EK-1 kernel",
                "parameters": [
                    {
                        "description": "Message and conversation history",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_chat.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_chat.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/chat/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Get conversation history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max messages to return (1–200, default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_chat.Message"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/chat/stream": {
            "post": {
                "description": "Returns tokens as Server-Sent Events: {\"token\":\"\u003cchunk\u003e\"} until {\"done\":true,\"timestamp\":\"...\"}. Falls back to buffered JSON when streaming is unavailable.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Stream chat with your EK-1 kernel (SSE)",
                "parameters": [
                    {
                        "description": "Message and conversation history",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_chat.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/harvest/results": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "harvest"
                ],
                "summary": "Get latest harvest results",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_harvest.HarvestResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/harvest/scan": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "harvest"
                ],
                "summary": "Run harvest scan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_harvest.HarvestResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/integrations/services": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "List all services",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_integrations.Service"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/integrations/services/custom": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Create custom service",
                "parameters": [
                    {
                        "description": "Custom service (name, category, api_endpoint, api_key required)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_integrations.Service"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_integrations.Service"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/integrations/services/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Get service by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_integrations.Service"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/integrations/services/{id}/connect": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Complete connecting a service",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Credentials (api_key or oauth_access_token)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_integrations.ConnectInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_integrations.Service"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Start connecting a service",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_integrations.Service"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "For OAuth services, attempts token revocation before clearing credentials.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Disconnect / uninstall a service",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_integrations.Service"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/integrations/services/{id}/oauth-app": {
            "post": {
                "description": "Encrypts and stores the user's OAuth client_id and client_secret at rest.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Save OAuth app credentials (BYOA — step 9a)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "client_id and client_secret",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_integrations.oauthAppRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "invalid_credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "service_not_found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/integrations/services/{id}/oauth/initiate": {
            "post": {
                "description": "Generates a PKCE code_verifier/challenge and CSRF state, then returns the",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Initiate OAuth2 authorization flow (step 9b)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_integrations.initiateOAuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "app_not_configured",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ledger/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ledger"
                ],
                "summary": "Get reputation history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Results per page (1–100, default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_ledger.HistoryEntry"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ledger/score": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ledger"
                ],
                "summary": "Get reputation score",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List unread notifications",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_notifications.Notification"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/read-all": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Mark all notifications as read",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/{id}/read": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Mark notification as read",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Notification ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/oauth/callback": {
            "get": {
                "description": "Receives the authorization code from the third-party redirect, exchanges it",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "OAuth2 callback handler (step 9c)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code from provider",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "CSRF state token",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Regional token endpoint base (Zoho)",
                        "name": "accounts-server",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Self-closing HTML page"
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_profile.Profile"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/profile/connection": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update connection settings",
                "parameters": [
                    {
                        "description": "Connection settings",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_profile.ConnectionSetting"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_profile.Profile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/profile/pin": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Store the screen lock PIN hash",
                "parameters": [
                    {
                        "description": "SHA-256 hex of the PIN (64 chars)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.pinReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Remove the screen lock PIN",
                "parameters": [
                    {
                        "description": "Current PIN hash for verification",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.pinReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/profile/preferences": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update decision preferences",
                "parameters": [
                    {
                        "description": "Preference weights (1–10 each)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_profile.DecisionPreference"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_profile.Profile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/scheduler/run-now": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scheduler"
                ],
                "summary": "Trigger immediate pipeline cycle",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_scheduler.RunNowResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/scheduler/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scheduler"
                ],
                "summary": "Get scheduler status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_scheduler.Status"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_egokernel_ek1_internal_brain.PipelineResult": {
            "type": "object",
            "properties": {
                "accepted": {
                    "description": "passed Triage + Decide → Decision: Automated",
                    "type": "integer"
                },
                "ghosted": {
                    "description": "manipulation detected → Decision: Declined (ghost)",
                    "type": "integer"
                },
                "rejected": {
                    "description": "failed Triage or Decide → Decision: Declined",
                    "type": "integer"
                },
                "shield_reason": {
                    "description": "why shield was active",
                    "type": "string"
                },
                "shielded": {
                    "description": "biometrics gate was active during this run",
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_egokernel_ek1_internal_datasync.ServiceStatus": {
            "type": "object",
            "properties": {
                "last_error": {
                    "type": "string"
                },
                "last_sync_at": {
                    "description": "nil = never synced",
                    "type": "string"
                },
                "signal_count": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "internal_activities.Decision": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "Pending",
                "Accepted",
                "Declined",
                "Negotiated",
                "Automated",
                "Cancelled"
            ]
        },
        "internal_activities.Event": {
            "type": "object",
            "properties": {
                "analysis": {
                    "description": "LLM scores + triage rationale",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_activities.SignalAnalysis"
                        }
                    ]
                },
                "created_at": {
                    "type": "string"
                },
                "decision": {
                    "enum": [
                        0,
                        1,
                        2,
                        3,
                        4,
                        5
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_activities.Decision"
                        }
                    ]
                },
                "event_type": {
                    "enum": [
                        0,
                        1,
                        2,
                        3,
                        4,
                        5
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_activities.EventType"
                        }
                    ]
                },
                "gain": {
                    "$ref": "#/definitions/internal_activities.Gain"
                },
                "id": {
                    "type": "integer"
                },
                "importance": {
                    "enum": [
                        0,
                        1,
                        2
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_activities.Importance"
                        }
                    ]
                },
                "narrative": {
                    "description": "Detail description of exactly what happened",
                    "type": "string"
                },
                "read": {
                    "type": "boolean"
                },
                "source_service": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_activities.EventType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "Finance",
                "Calendar",
                "Communication",
                "Billing",
                "Health",
                "Other"
            ]
        },
        "internal_activities.Gain": {
            "type": "object",
            "properties": {
                "_symbol": {
                    "description": "How to present the gain e.g $ for money type",
                    "type": "string"
                },
                "_value": {
                    "type": "number"
                },
                "details": {
                    "type": "string"
                },
                "kind": {
                    "enum": [
                        0,
                        1
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_activities.GainKind"
                        }
                    ]
                },
                "type": {
                    "enum": [
                        0,
                        1
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_activities.GainType"
                        }
                    ]
                }
            }
        },
        "internal_activities.GainKind": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "Money",
                "Time"
            ]
        },
        "internal_activities.GainType": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "Positive",
                "Negative"
            ]
        },
        "internal_activities.Importance": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "Low",
                "Medium",
                "High"
            ]
        },
        "internal_activities.SignalAnalysis": {
            "type": "object",
            "properties": {
                "decide_threshold": {
                    "description": "utility threshold at time of Decide",
                    "type": "number"
                },
                "decide_utility": {
                    "description": "utility computed by Decide (if reached)",
                    "type": "number"
                },
                "estimated_roi": {
                    "description": "USD value scored by LLM",
                    "type": "number"
                },
                "manipulation_pct": {
                    "description": "0–1 manipulation score",
                    "type": "number"
                },
                "roi_threshold": {
                    "description": "minimum ROI the kernel required at triage",
                    "type": "number"
                },
                "service_slug": {
                    "type": "string"
                },
                "signal_title": {
                    "type": "string"
                },
                "time_commitment": {
                    "description": "hours scored by LLM",
                    "type": "number"
                },
                "triage_gate": {
                    "description": "financial_insignificance | manipulation | decide_utility | decide_risk | accepted",
                    "type": "string"
                }
            }
        },
        "internal_auth.pinReq": {
            "type": "object",
            "properties": {
                "pin_hash": {
                    "type": "string"
                }
            }
        },
        "internal_auth.unlockReq": {
            "type": "object",
            "properties": {
                "pin_hash": {
                    "type": "string"
                }
            }
        },
        "internal_biometrics.CheckIn": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "energy": {
                    "type": "integer"
                },
                "extra_context": {
                    "type": "string"
                },
                "mood": {
                    "type": "integer"
                },
                "sleep": {
                    "type": "number"
                },
                "stress_level": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_brain.KernelSnapshot": {
            "type": "object",
            "properties": {
                "decision_count": {
                    "type": "integer"
                },
                "identity_entropy": {
                    "type": "number"
                },
                "status": {
                    "description": "Status is the current operational mode of the kernel.\nONLINE: normal autonomous operation.\nSHIELDED: biometrics gate active — elevated stress or poor sleep; decision threshold raised.\nH2HI: identity entropy spike — manual review required; call POST /brain/sync-acknowledge to resume.\nEXILED: reputation score below exile threshold; no external processing.\nenums: ONLINE,SHIELDED,H2HI,EXILED",
                    "type": "string",
                    "enum": [
                        "ONLINE",
                        "SHIELDED",
                        "H2HI",
                        "EXILED"
                    ]
                },
                "values": {
                    "$ref": "#/definitions/internal_brain.ValueMatrix"
                }
            }
        },
        "internal_brain.StageProgress": {
            "type": "object",
            "properties": {
                "hand": {
                    "type": "integer"
                },
                "shadow": {
                    "type": "integer"
                },
                "voice": {
                    "type": "integer"
                }
            }
        },
        "internal_brain.StatusResponse": {
            "type": "object",
            "properties": {
                "decision_count": {
                    "type": "integer"
                },
                "identity_entropy": {
                    "type": "number"
                },
                "reputation_score": {
                    "type": "integer"
                },
                "reputation_tier": {
                    "type": "string"
                },
                "stage_progress": {
                    "$ref": "#/definitions/internal_brain.StageProgress"
                },
                "status": {
                    "description": "Status is the current operational mode of the kernel.\nONLINE: normal autonomous operation.\nSHIELDED: biometrics gate active — elevated stress or poor sleep; decision threshold raised.\nH2HI: identity entropy spike — manual review required; call POST /brain/sync-acknowledge to resume.\nEXILED: reputation score below exile threshold; no external processing.\nenums: ONLINE,SHIELDED,H2HI,EXILED",
                    "type": "string",
                    "enum": [
                        "ONLINE",
                        "SHIELDED",
                        "H2HI",
                        "EXILED"
                    ]
                },
                "time_saved_today": {
                    "description": "minutes",
                    "type": "integer"
                },
                "values": {
                    "$ref": "#/definitions/internal_brain.ValueMatrix"
                }
            }
        },
        "internal_brain.ValueMatrix": {
            "type": "object",
            "properties": {
                "baseHourlyRate": {
                    "description": "BaseHourlyRate is the user's baseline value of one hour (in USD).\nUsed to compute the Cognitive Tax on time-consuming opportunities.",
                    "type": "number",
                    "format": "float64"
                },
                "presentBiasDiscount": {
                    "description": "PresentBiasDiscount (ρ) is the user's personal discount rate for future rewards.\nHigher ρ = more present-biased (prefers immediate gains).",
                    "type": "number",
                    "format": "float64"
                },
                "reputationImpact": {
                    "description": "ReputationImpact: how much the user cares about ledger cleanliness (0–1).\nHIGH priority. Predatory trades incur a reputation cost.",
                    "type": "number",
                    "format": "float64"
                },
                "riskTolerance": {
                    "description": "RiskTolerance: 0.05 = very conservative, 0.90 = degen.\nMEDIUM priority. Mapped to a configurable σ.",
                    "type": "number",
                    "format": "float64"
                },
                "socialEntropy": {
                    "description": "SocialEntropy: desire to maintain human-like friction (prevents appearing robotic).\nLOW priority. Set \u003e 0 to inject periodic \"irrational\" human choices.",
                    "type": "number",
                    "format": "float64"
                },
                "temporalSovereignty": {
                    "description": "TemporalSovereignty: how much the user values unstructured free time (0–1).\nCRITICAL priority. Any interaction yielding \u003c 1.5× ROI on attention is culled.",
                    "type": "number",
                    "format": "float64"
                },
                "utilityThreshold": {
                    "description": "UtilityThreshold is the minimum computed utility required to execute an action.\nActions below this are automatically culled.",
                    "type": "number",
                    "format": "float64"
                }
            }
        },
        "internal_chat.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_chat.Request": {
            "type": "object",
            "properties": {
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_chat.Message"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_chat.Response": {
            "type": "object",
            "properties": {
                "reply": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_harvest.ContactRecord": {
            "type": "object",
            "properties": {
                "favors_given": {
                    "description": "favours the contact gave to the user",
                    "type": "integer"
                },
                "favors_received": {
                    "description": "favours the contact received from the user",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_contact": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "overlap": {
                    "description": "max 0-1 solution/bottleneck similarity seen",
                    "type": "number"
                }
            }
        },
        "internal_harvest.HarvestResult": {
            "type": "object",
            "properties": {
                "contacts_found": {
                    "type": "integer"
                },
                "debts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_harvest.SocialDebt"
                    }
                },
                "opportunities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scanned_at": {
                    "type": "string"
                },
                "total_value": {
                    "type": "number"
                }
            }
        },
        "internal_harvest.SocialDebt": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "recommended next step",
                    "type": "string"
                },
                "contact": {
                    "$ref": "#/definitions/internal_harvest.ContactRecord"
                },
                "estimated_value": {
                    "description": "USD equivalent",
                    "type": "number"
                },
                "net_favors": {
                    "description": "positive = contact owes the user",
                    "type": "integer"
                }
            }
        },
        "internal_integrations.AuthMethod": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "APIKeyAuth",
                "OAuth2Auth"
            ]
        },
        "internal_integrations.ConnectInput": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "oauth_access_token": {
                    "type": "string"
                },
                "oauth_refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_integrations.ConnectionStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "Connected": "connected and active",
                "Disconnected": "not installed",
                "Pending": "credentials being entered"
            },
            "x-enum-descriptions": [
                "not installed",
                "credentials being entered",
                "connected and active"
            ],
            "x-enum-varnames": [
                "Disconnected",
                "Pending",
                "Connected"
            ]
        },
        "internal_integrations.Service": {
            "type": "object",
            "properties": {
                "api_endpoint": {
                    "type": "string"
                },
                "api_key": {
                    "description": "masked on read, never raw",
                    "type": "string"
                },
                "app_configured": {
                    "description": "AppConfigured is true once the user has saved their OAuth client_id/secret (BYOA).\nfalse → show \"Set Up OAuth App\"; true + !OAuthConnected → show \"Authorize\"; true + OAuthConnected → show \"Disconnect\"",
                    "type": "boolean"
                },
                "auth_method": {
                    "enum": [
                        0,
                        1
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_integrations.AuthMethod"
                        }
                    ]
                },
                "category": {
                    "type": "string"
                },
                "color": {
                    "description": "brand hex color, e.g. \"#4285F4\"; empty for custom services",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "custom": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "oauth_connected": {
                    "type": "boolean"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        0,
                        1,
                        2
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_integrations.ConnectionStatus"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_integrations.initiateOAuthResponse": {
            "type": "object",
            "properties": {
                "auth_url": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "internal_integrations.oauthAppRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                }
            }
        },
        "internal_ledger.HistoryEntry": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "impact": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_notifications.Notification": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "read": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/internal_notifications.Type"
                }
            }
        },
        "internal_notifications.Type": {
            "type": "string",
            "enum": [
                "H2HI",
                "OPPORTUNITY",
                "HARVEST",
                "SOUL_DRIFT"
            ],
            "x-enum-comments": {
                "TypeH2HI": "identity entropy spike — manual sync required",
                "TypeHarvest": "ghost-agreement opportunity detected",
                "TypeOpportunity": "high-value social debt detected by harvest engine",
                "TypeSoulDrift": "periodic irrational-human injection event"
            },
            "x-enum-descriptions": [
                "identity entropy spike — manual sync required",
                "high-value social debt detected by harvest engine",
                "ghost-agreement opportunity detected",
                "periodic irrational-human injection event"
            ],
            "x-enum-varnames": [
                "TypeH2HI",
                "TypeOpportunity",
                "TypeHarvest",
                "TypeSoulDrift"
            ]
        },
        "internal_profile.ConnectionSetting": {
            "type": "object",
            "properties": {
                "api_endpoint": {
                    "type": "string"
                },
                "kernel_name": {
                    "type": "string"
                },
                "timezone": {
                    "description": "IANA timezone name e.g. \"Europe/London\", \"UTC\"",
                    "type": "string"
                }
            }
        },
        "internal_profile.DecisionPreference": {
            "type": "object",
            "properties": {
                "autonomy": {
                    "description": "Minimise dependence on third parties",
                    "type": "integer"
                },
                "financial_growth": {
                    "description": "Prioritise revenue-generating decisions",
                    "type": "integer"
                },
                "health_recovery": {
                    "description": "Respect sleep, stress and energy limits",
                    "type": "integer"
                },
                "privacy_protection": {
                    "description": "Refuse data sharing with low-trust parties",
                    "type": "integer"
                },
                "reputation_building": {
                    "description": "Long-term trust over short-term gain",
                    "type": "integer"
                },
                "time_sovereignty": {
                    "description": "Weight given to protecting your time",
                    "type": "integer"
                }
            }
        },
        "internal_profile.EKProgress": {
            "type": "object",
            "properties": {
                "hand": {
                    "type": "boolean"
                },
                "shadow": {
                    "type": "boolean"
                },
                "voice": {
                    "type": "boolean"
                }
            }
        },
        "internal_profile.Profile": {
            "type": "object",
            "properties": {
                "api_endpoint": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "has_pin": {
                    "type": "boolean"
                },
                "kernel_name": {
                    "type": "string"
                },
                "preferences": {
                    "$ref": "#/definitions/internal_profile.DecisionPreference"
                },
                "progress": {
                    "$ref": "#/definitions/internal_profile.EKProgress"
                },
                "timezone": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_scheduler.RunNowResponse": {
            "type": "object",
            "properties": {
                "accepted": {
                    "description": "passed Triage + Decide → Decision: Automated",
                    "type": "integer"
                },
                "ghosted": {
                    "description": "manipulation detected → Decision: Declined (ghost)",
                    "type": "integer"
                },
                "rejected": {
                    "description": "failed Triage or Decide → Decision: Declined",
                    "type": "integer"
                },
                "shield_reason": {
                    "description": "why shield was active",
                    "type": "string"
                },
                "shielded": {
                    "description": "biometrics gate was active during this run",
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_scheduler.Status": {
            "type": "object",
            "properties": {
                "interval_minutes": {
                    "type": "integer"
                },
                "last_error": {
                    "description": "non-empty when last cycle failed",
                    "type": "string"
                },
                "last_result": {
                    "description": "nil if never run",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_egokernel_ek1_internal_brain.PipelineResult"
                        }
                    ]
                },
                "last_run_at": {
                    "description": "nil if never run",
                    "type": "string"
                },
                "last_signal_count": {
                    "type": "integer"
                },
                "next_run_at": {
                    "description": "nil if not started",
                    "type": "string"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_egokernel_ek1_internal_datasync.ServiceStatus"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "EK-1 Ego-Kernel API",
	Description:      "Personal AI agent — calendar, email, finance & negotiations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
