// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/activities/events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "List events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/activities.Event"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/activities/events/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Get event by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/activities.Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/activities/events/{id}/read": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Toggle read status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/activities.Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/biometrics/checkin": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "biometrics"
                ],
                "summary": "Get current check-in",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/biometrics.CheckIn"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "biometrics"
                ],
                "summary": "Update check-in",
                "parameters": [
                    {
                        "description": "Check-in data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/biometrics.CheckIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/biometrics.CheckIn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/biometrics/checkin/history": {
            "get": {
                "description": "Returns past check-ins newest first. Default limit is 7 (one week); maximum is 90.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "biometrics"
                ],
                "summary": "Check-in history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of entries to return (1–90, default 7)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/biometrics.CheckIn"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/brain/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "brain"
                ],
                "summary": "Get brain status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/brain.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/brain/sync-acknowledge": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "brain"
                ],
                "summary": "Acknowledge manual sync (clears H2HI)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/brain.KernelSnapshot"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/chat": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat with your EK-1 kernel",
                "parameters": [
                    {
                        "description": "Message and conversation history",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chat.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chat.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/chat/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Get conversation history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max messages to return (1–200, default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/chat.Message"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/harvest/results": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "harvest"
                ],
                "summary": "Get latest harvest results",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/harvest.HarvestResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/harvest/scan": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "harvest"
                ],
                "summary": "Run harvest scan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/harvest.HarvestResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/integrations/services": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "List all services",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/integrations.Service"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/integrations/services/custom": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Create custom service",
                "parameters": [
                    {
                        "description": "Custom service (name, category, api_endpoint, api_key required)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/integrations.Service"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/integrations.Service"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/integrations/services/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Get service by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.Service"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/integrations/services/{id}/connect": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Complete connecting a service",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Credentials (api_key or oauth_access_token)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/integrations.ConnectInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.Service"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Start connecting a service",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.Service"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Uninstall a service",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/integrations.Service"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ledger/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ledger"
                ],
                "summary": "Get reputation history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Results per page (1–100, default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ledger.HistoryEntry"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ledger/score": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ledger"
                ],
                "summary": "Get reputation score",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List unread notifications",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/notifications.Notification"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/read-all": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Mark all notifications as read",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/notifications/{id}/read": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Mark notification as read",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Notification ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/profile.Profile"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/profile/connection": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update connection settings",
                "parameters": [
                    {
                        "description": "Connection settings",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.ConnectionSetting"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/profile.Profile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/profile/preferences": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update decision preferences",
                "parameters": [
                    {
                        "description": "Preference weights (1–10 each)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.DecisionPreference"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/profile.Profile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/scheduler/run-now": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scheduler"
                ],
                "summary": "Trigger immediate pipeline cycle",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/brain.PipelineResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/scheduler/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scheduler"
                ],
                "summary": "Get scheduler status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/scheduler.Status"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "activities.Decision": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "Pending",
                "Accepted",
                "Declined",
                "Negotiated",
                "Automated",
                "Cancelled"
            ]
        },
        "activities.Event": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "decision": {
                    "enum": [
                        0,
                        1,
                        2,
                        3,
                        4,
                        5
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/activities.Decision"
                        }
                    ]
                },
                "event_type": {
                    "enum": [
                        0,
                        1,
                        2,
                        3,
                        4,
                        5
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/activities.EventType"
                        }
                    ]
                },
                "gain": {
                    "$ref": "#/definitions/activities.Gain"
                },
                "id": {
                    "type": "integer"
                },
                "importance": {
                    "enum": [
                        0,
                        1,
                        2
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/activities.Importance"
                        }
                    ]
                },
                "narrative": {
                    "description": "Detail description of exactly what happened",
                    "type": "string"
                },
                "read": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "activities.EventType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "Finance",
                "Calendar",
                "Communication",
                "Billing",
                "Health",
                "Other"
            ]
        },
        "activities.Gain": {
            "type": "object",
            "properties": {
                "_symbol": {
                    "description": "How to present the gain e.g $ for money type",
                    "type": "string"
                },
                "_value": {
                    "type": "number"
                },
                "details": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        0,
                        1
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/activities.GainType"
                        }
                    ]
                }
            }
        },
        "activities.GainType": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "Positive",
                "Negative"
            ]
        },
        "activities.Importance": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "Low",
                "Medium",
                "High"
            ]
        },
        "biometrics.CheckIn": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "energy": {
                    "type": "integer"
                },
                "extra_context": {
                    "type": "string"
                },
                "mood": {
                    "type": "integer"
                },
                "sleep": {
                    "type": "number"
                },
                "stress_level": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "brain.KernelSnapshot": {
            "type": "object",
            "properties": {
                "decision_count": {
                    "type": "integer"
                },
                "identity_entropy": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "values": {
                    "$ref": "#/definitions/brain.ValueMatrix"
                }
            }
        },
        "brain.PipelineResult": {
            "type": "object",
            "properties": {
                "accepted": {
                    "description": "passed Triage + Decide → Decision: Automated",
                    "type": "integer"
                },
                "ghosted": {
                    "description": "manipulation detected → Decision: Declined (ghost)",
                    "type": "integer"
                },
                "rejected": {
                    "description": "failed Triage or Decide → Decision: Declined",
                    "type": "integer"
                },
                "shield_reason": {
                    "description": "why shield was active",
                    "type": "string"
                },
                "shielded": {
                    "description": "biometrics gate was active during this run",
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "brain.StageProgress": {
            "type": "object",
            "properties": {
                "hand": {
                    "type": "integer"
                },
                "shadow": {
                    "type": "integer"
                },
                "voice": {
                    "type": "integer"
                }
            }
        },
        "brain.StatusResponse": {
            "type": "object",
            "properties": {
                "decision_count": {
                    "type": "integer"
                },
                "identity_entropy": {
                    "type": "number"
                },
                "reputation_score": {
                    "type": "integer"
                },
                "reputation_tier": {
                    "type": "string"
                },
                "stage_progress": {
                    "$ref": "#/definitions/brain.StageProgress"
                },
                "status": {
                    "type": "string"
                },
                "time_saved_today": {
                    "description": "minutes",
                    "type": "integer"
                },
                "values": {
                    "$ref": "#/definitions/brain.ValueMatrix"
                }
            }
        },
        "brain.ValueMatrix": {
            "type": "object",
            "properties": {
                "baseHourlyRate": {
                    "description": "BaseHourlyRate is the user's baseline value of one hour (in USD).\nUsed to compute the Cognitive Tax on time-consuming opportunities.",
                    "type": "number",
                    "format": "float64"
                },
                "presentBiasDiscount": {
                    "description": "PresentBiasDiscount (ρ) is the user's personal discount rate for future rewards.\nHigher ρ = more present-biased (prefers immediate gains).",
                    "type": "number",
                    "format": "float64"
                },
                "reputationImpact": {
                    "description": "ReputationImpact: how much the user cares about ledger cleanliness (0–1).\nHIGH priority. Predatory trades incur a reputation cost.",
                    "type": "number",
                    "format": "float64"
                },
                "riskTolerance": {
                    "description": "RiskTolerance: 0.05 = very conservative, 0.90 = degen.\nMEDIUM priority. Mapped to a configurable σ.",
                    "type": "number",
                    "format": "float64"
                },
                "socialEntropy": {
                    "description": "SocialEntropy: desire to maintain human-like friction (prevents appearing robotic).\nLOW priority. Set \u003e 0 to inject periodic \"irrational\" human choices.",
                    "type": "number",
                    "format": "float64"
                },
                "temporalSovereignty": {
                    "description": "TemporalSovereignty: how much the user values unstructured free time (0–1).\nCRITICAL priority. Any interaction yielding \u003c 1.5× ROI on attention is culled.",
                    "type": "number",
                    "format": "float64"
                },
                "utilityThreshold": {
                    "description": "UtilityThreshold is the minimum computed utility required to execute an action.\nActions below this are automatically culled.",
                    "type": "number",
                    "format": "float64"
                }
            }
        },
        "chat.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "chat.Request": {
            "type": "object",
            "properties": {
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/chat.Message"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "chat.Response": {
            "type": "object",
            "properties": {
                "reply": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "harvest.ContactRecord": {
            "type": "object",
            "properties": {
                "favors_given": {
                    "description": "favours the contact gave to the user",
                    "type": "integer"
                },
                "favors_received": {
                    "description": "favours the contact received from the user",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_contact": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "overlap": {
                    "description": "max 0-1 solution/bottleneck similarity seen",
                    "type": "number"
                }
            }
        },
        "harvest.HarvestResult": {
            "type": "object",
            "properties": {
                "contacts_found": {
                    "type": "integer"
                },
                "debts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/harvest.SocialDebt"
                    }
                },
                "opportunities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scanned_at": {
                    "type": "string"
                },
                "total_value": {
                    "type": "number"
                }
            }
        },
        "harvest.SocialDebt": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "recommended next step",
                    "type": "string"
                },
                "contact": {
                    "$ref": "#/definitions/harvest.ContactRecord"
                },
                "estimated_value": {
                    "description": "USD equivalent",
                    "type": "number"
                },
                "net_favors": {
                    "description": "positive = contact owes the user",
                    "type": "integer"
                }
            }
        },
        "integrations.AuthMethod": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "APIKeyAuth",
                "OAuth2Auth"
            ]
        },
        "integrations.ConnectInput": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "oauth_access_token": {
                    "type": "string"
                },
                "oauth_refresh_token": {
                    "type": "string"
                }
            }
        },
        "integrations.ConnectionStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "Connected": "connected and active",
                "Disconnected": "not installed",
                "Pending": "credentials being entered"
            },
            "x-enum-descriptions": [
                "not installed",
                "credentials being entered",
                "connected and active"
            ],
            "x-enum-varnames": [
                "Disconnected",
                "Pending",
                "Connected"
            ]
        },
        "integrations.Service": {
            "type": "object",
            "properties": {
                "api_endpoint": {
                    "type": "string"
                },
                "api_key": {
                    "description": "masked on read, never raw",
                    "type": "string"
                },
                "auth_method": {
                    "enum": [
                        0,
                        1
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/integrations.AuthMethod"
                        }
                    ]
                },
                "category": {
                    "type": "string"
                },
                "color": {
                    "description": "brand hex color, e.g. \"#4285F4\"; empty for custom services",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "custom": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "oauth_connected": {
                    "type": "boolean"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        0,
                        1,
                        2
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/integrations.ConnectionStatus"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "ledger.HistoryEntry": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "impact": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "notifications.Notification": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "read": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/notifications.Type"
                }
            }
        },
        "notifications.Type": {
            "type": "string",
            "enum": [
                "H2HI",
                "OPPORTUNITY",
                "HARVEST",
                "SOUL_DRIFT"
            ],
            "x-enum-comments": {
                "TypeH2HI": "identity entropy spike — manual sync required",
                "TypeHarvest": "ghost-agreement opportunity detected",
                "TypeOpportunity": "high-value social debt detected by harvest engine",
                "TypeSoulDrift": "periodic irrational-human injection event"
            },
            "x-enum-descriptions": [
                "identity entropy spike — manual sync required",
                "high-value social debt detected by harvest engine",
                "ghost-agreement opportunity detected",
                "periodic irrational-human injection event"
            ],
            "x-enum-varnames": [
                "TypeH2HI",
                "TypeOpportunity",
                "TypeHarvest",
                "TypeSoulDrift"
            ]
        },
        "profile.ConnectionSetting": {
            "type": "object",
            "properties": {
                "api_endpoint": {
                    "type": "string"
                },
                "kernel_name": {
                    "type": "string"
                },
                "timezone": {
                    "description": "IANA timezone name e.g. \"Europe/London\", \"UTC\"",
                    "type": "string"
                }
            }
        },
        "profile.DecisionPreference": {
            "type": "object",
            "properties": {
                "autonomy": {
                    "description": "Minimise dependence on third parties",
                    "type": "integer"
                },
                "financial_growth": {
                    "description": "Prioritise revenue-generating decisions",
                    "type": "integer"
                },
                "health_recovery": {
                    "description": "Respect sleep, stress and energy limits",
                    "type": "integer"
                },
                "privacy_protection": {
                    "description": "Refuse data sharing with low-trust parties",
                    "type": "integer"
                },
                "reputation_building": {
                    "description": "Long-term trust over short-term gain",
                    "type": "integer"
                },
                "time_sovereignty": {
                    "description": "Weight given to protecting your time",
                    "type": "integer"
                }
            }
        },
        "profile.EKProgress": {
            "type": "object",
            "properties": {
                "hand": {
                    "type": "boolean"
                },
                "shadow": {
                    "type": "boolean"
                },
                "voice": {
                    "type": "boolean"
                }
            }
        },
        "profile.Profile": {
            "type": "object",
            "properties": {
                "api_endpoint": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "kernel_name": {
                    "type": "string"
                },
                "preferences": {
                    "$ref": "#/definitions/profile.DecisionPreference"
                },
                "progress": {
                    "$ref": "#/definitions/profile.EKProgress"
                },
                "timezone": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "scheduler.Status": {
            "type": "object",
            "properties": {
                "interval_minutes": {
                    "type": "integer"
                },
                "last_result": {
                    "description": "nil if never run",
                    "allOf": [
                        {
                            "$ref": "#/definitions/brain.PipelineResult"
                        }
                    ]
                },
                "last_run_at": {
                    "description": "nil if never run",
                    "type": "string"
                },
                "last_signal_count": {
                    "type": "integer"
                },
                "next_run_at": {
                    "description": "nil if not started",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "EK-1 Ego-Kernel API",
	Description:      "Personal AI agent — calendar, email, finance & negotiations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
