# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ner_pb2 as ner__pb2


class NERServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Annotate = channel.unary_unary(
                '/ner.NERService/Annotate',
                request_serializer=ner__pb2.AnnotateRequest.SerializeToString,
                response_deserializer=ner__pb2.AnnotateResponse.FromString,
                )
        self.BatchAnnotate = channel.unary_unary(
                '/ner.NERService/BatchAnnotate',
                request_serializer=ner__pb2.BatchAnnotateRequest.SerializeToString,
                response_deserializer=ner__pb2.BatchAnnotateResponse.FromString,
                )


class NERServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Annotate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchAnnotate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NERServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Annotate': grpc.unary_unary_rpc_method_handler(
                    servicer.Annotate,
                    request_deserializer=ner__pb2.AnnotateRequest.FromString,
                    response_serializer=ner__pb2.AnnotateResponse.SerializeToString,
            ),
            'BatchAnnotate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchAnnotate,
                    request_deserializer=ner__pb2.BatchAnnotateRequest.FromString,
                    response_serializer=ner__pb2.BatchAnnotateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ner.NERService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NERService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Annotate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ner.NERService/Annotate',
            ner__pb2.AnnotateRequest.SerializeToString,
            ner__pb2.AnnotateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchAnnotate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ner.NERService/BatchAnnotate',
            ner__pb2.BatchAnnotateRequest.SerializeToString,
            ner__pb2.BatchAnnotateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
