# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tner.proto\x12\x03ner\"B\n\x0f\x41nnotateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06labels\x18\x02 \x03(\t\x12\x11\n\tthreshold\x18\x03 \x01(\x02\"N\n\x04Span\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x12\r\n\x05label\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x02\x12\x0c\n\x04text\x18\x05 \x01(\t\"J\n\x10\x41nnotateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06tokens\x18\x02 \x03(\t\x12\x18\n\x05spans\x18\x03 \x03(\x0b\x32\t.ner.Span\"H\n\x14\x42\x61tchAnnotateRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x0e\n\x06labels\x18\x02 \x03(\t\x12\x11\n\tthreshold\x18\x03 \x01(\x02\"C\n\x15\x42\x61tchAnnotateResponse\x12*\n\x0b\x61nnotations\x18\x01 \x03(\x0b\x32\x15.ner.AnnotateResponse2\x8d\x01\n\nNERService\x12\x37\n\x08\x41nnotate\x12\x14.ner.AnnotateRequest\x1a\x15.ner.AnnotateResponse\x12\x46\n\rBatchAnnotate\x12\x19.ner.BatchAnnotateRequest\x1a\x1a.ner.BatchAnnotateResponseB4Z2github.com/ContinuumSolutions/nonym/pkg/ner/ner_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ner_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/ContinuumSolutions/nonym/pkg/ner/ner_pb'
  _globals['_ANNOTATEREQUEST']._serialized_start=18
  _globals['_ANNOTATEREQUEST']._serialized_end=84
  _globals['_SPAN']._serialized_start=86
  _globals['_SPAN']._serialized_end=164
  _globals['_ANNOTATERESPONSE']._serialized_start=166
  _globals['_ANNOTATERESPONSE']._serialized_end=240
  _globals['_BATCHANNOTATEREQUEST']._serialized_start=242
  _globals['_BATCHANNOTATEREQUEST']._serialized_end=314
  _globals['_BATCHANNOTATERESPONSE']._serialized_start=316
  _globals['_BATCHANNOTATERESPONSE']._serialized_end=383
  _globals['_NERSERVICE']._serialized_start=386
  _globals['_NERSERVICE']._serialized_end=527
# @@protoc_insertion_point(module_scope)
